apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana_image
          name: grafana
          imagePullPolicy: Never
          ports:
            - containerPort: 3000