
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  name: wp-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 5050
      name: wp-port
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress_image
          imagePullPolicy: Never
          ports:
            - containerPort: 5050


#apiVersion: v1
#kind: Service
#metadata:
#  name: wordpress-svc
#  labels:
#    metallb.universe.tf/allow-shared-ip: default
#spec:
#  type: LoadBalancer
#  loadBalancerIP: 192.168.99.100
#  selector:
#    app: wordpress
#  ports:
#    - port: 5050
#      protocol: TCP
#      name : wordpress-port
#      targetPort: 5050
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: wordpress-deployment
#spec:
#  selector:
#    matchLabels:
#      app: wordpress
#  strategy:
#    type: Recreate
#  template:
#    metadata:
#      labels:
#        app: wordpress
#    spec:
#      containers:
#        - name: wordpress
#          image: wordpress_image
#          imagePullPolicy: Never
#          ports:
#          - containerPort: 5050